tracer-samples/pom.xml, tracer-samples/tracer-sample-with-sofarpc/README.md, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-sofarpc/src/main/java/com/alipay/sofa/tracer/examples/sofarpc/direct/DirectClientApplication.java, tracer-samples/tracer-sample-with-sofarpc/src/main/java/com/alipay/sofa/tracer/examples/sofarpc/direct/DirectServerApplication.java, tracer-samples/tracer-sample-with-sofarpc/src/main/java/com/alipay/sofa/tracer/examples/sofarpc/direct/DirectService.java, tracer-samples/tracer-sample-with-sofarpc/src/main/java/com/alipay/sofa/tracer/examples/sofarpc/direct/DirectServiceImpl.java, tracer-samples/tracer-sample-with-sofarpc/src/main/resources/application.properties, tracer-samples/tracer-sample-with-sofarpc/src/main/resources/direct-client-example.xml, tracer-samples/tracer-sample-with-sofarpc/src/main/resources/direct-server-example.xml
=> add sofarpc example for rpc 5.4.0

tracer-core/src/main/java/com/alipay/common/tracer/core/reporter/stat/manager/SofaTracerStatisticReporterManager.java
Fix It
https://github.com/alipay/sofa-tracer/issues/26
=> fix daemon bug

pom.xml, tracer-samples/tracer-sample-with-sofarpc/README.md, tracer-samples/tracer-sample-with-springmvc/README.md, tracer-sofa-boot-plugin/pom.xml
=> Tracer ark plugin

pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Upgrade 2.1.3

pom.xml, tracer-samples/tracer-sample-with-slf4j/README.md, tracer-samples/tracer-sample-with-sofarpc/README.md, tracer-samples/tracer-sample-with-springmvc/README.md, tracer-samples/tracer-sample-with-zipkin/README.md, tracer-sofa-boot-plugin/pom.xml
=> Cherry pick new ark plugin.

tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/configuration/SofaTracerAutoConfiguration.java, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java
=> Optimize auto-configuration.

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/README.md, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
Upgrade to 2.2.1-SNAPSHOT version.
=> Upgrade to snapshot version.

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/README.md, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> upgrade to snapshot version (#82)

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/configuration/SofaTracerAutoConfiguration.java
=> upgrade 2.2.2-snap-shot

tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/configuration/SofaTracerAutoConfiguration.java, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/properties/SofaTracerProperties.java, tracer-sofa-boot-starter/src/main/resources/META-INF/spring.factories, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/ConfigurationTest.java, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/ConfigurationHolder.java, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/ConfigurationHolderListener.java, tracer-sofa-boot-starter/src/test/resources/META-INF/spring.factories, tracer-sofa-boot-starter/src/test/resources/application-config.properties
=> Advance assembly of sofaTracerConfiguration.

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/README.md, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/README.md, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/README.md, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/README.md, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/README.md, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/README.md, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Prepare release 2.2.2

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Upgrade version to 3.0.0

tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/annotation/ExcludeClasses.java, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/condition/ConditionOnClassTest.java, tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/junit/SeparateClassloaderTestRunner.java
OpenTracingSpringMvcAutoConfiguration add ConditionalOnClass SpringMvcSofaTracerFilter. #111
=> OpenTracingSpringMvcAutoConfiguration add ConditionalOnClass SpringMvcSofaTracerFilter

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-core/src/main/java/com/alipay/common/tracer/core/reporter/digest/manager/SofaTracerDigestReporterAsyncManager.java, tracer-core/src/main/java/com/alipay/common/tracer/core/reporter/stat/manager/SofaTracerStatisticReporterCycleTimesManager.java, tracer-core/src/test/java/com/alipay/common/tracer/core/reporter/digest/SofaTracerDigestReporterAsyncManagerTest.java, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Bugfix for npe

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Upgrade version 

tracer-sofa-boot-starter/pom.xml, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java, tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/zipkin/configuration/ZipkinSofaTracerAutoConfiguration.java
=> Fix webflux issue142

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> Upgrade version to 3.0.3

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-dubbo/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-consumer/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-facade/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-provider/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-resttemplate/pom.xml, tracer-samples/tracer-sample-with-sampler/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> upgrade to 2.4.1-SNAPSHOT

pom.xml, sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml, tracer-all/pom.xml, tracer-core/pom.xml, tracer-extensions/pom.xml, tracer-samples/pom.xml, tracer-samples/tracer-sample-with-dubbo/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-consumer/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-facade/pom.xml, tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-provider/pom.xml, tracer-samples/tracer-sample-with-h2/pom.xml, tracer-samples/tracer-sample-with-httpclient/pom.xml, tracer-samples/tracer-sample-with-openfeign/pom.xml, tracer-samples/tracer-sample-with-sampler/pom.xml, tracer-samples/tracer-sample-with-slf4j/pom.xml, tracer-samples/tracer-sample-with-sofarpc/pom.xml, tracer-samples/tracer-sample-with-springmvc/pom.xml, tracer-samples/tracer-sample-with-zipkin/pom.xml, tracer-sofa-boot-plugin/pom.xml, tracer-sofa-boot-starter/pom.xml, tracer-test/core-test/pom.xml, tracer-test/log4j-test/pom.xml, tracer-test/log4j2-test/pom.xml, tracer-test/logback-test/pom.xml
=> upgrade-3.0.5-SNAPSHOT

pom.xml, sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml, sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springcloud/instruments/feign/SofaTracerFeignClient.java, tracer-sofa-boot-starter/pom.xml
=> compatible feign 9.x 

tracer-samples/pom.xml, tracer-samples/tracer-sample-with-okhttp/pom.xml, tracer-samples/tracer-sample-with-okhttp/src/main/java/com/alipay/sofa/tracer/examples/okhttp/OkHttpDemoApplication.java, tracer-samples/tracer-sample-with-okhttp/src/main/java/com/alipay/sofa/tracer/examples/okhttp/controller/SampleRestController.java, tracer-samples/tracer-sample-with-okhttp/src/main/java/com/alipay/sofa/tracer/examples/okhttp/instance/OkHttpClientInstance.java, tracer-samples/tracer-sample-with-okhttp/src/main/resources/application.properties
=> Add okhttp samples
